"""empty message

Revision ID: 118142ec659e
Revises: 89ec80dd5654
Create Date: 2022-08-08 18:25:01.103533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118142ec659e'
down_revision = '89ec80dd5654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_venue_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.drop_column('show', 'venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_venue_fkey', 'show', 'venue', ['venue'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
