"""empty message

Revision ID: aedb879dce86
Revises: d9e7e751f585
Create Date: 2022-08-10 00:07:11.919286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedb879dce86'
down_revision = 'd9e7e751f585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
