"""empty message

Revision ID: cd2fb7f2c4ab
Revises: 5073bea32241
Create Date: 2022-08-08 18:13:25.872486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd2fb7f2c4ab'
down_revision = '5073bea32241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_dates',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.alter_column('show', 'venue',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('show', 'venue',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('show_dates')
    # ### end Alembic commands ###
