"""empty message

Revision ID: 6155ed245f62
Revises: 118142ec659e
Create Date: 2022-08-09 12:40:38.139119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6155ed245f62'
down_revision = '118142ec659e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_dates')
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.alter_column('show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('show', 'start_time')
    op.create_table('show_dates',
    sa.Column('show_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('show_id', name='show_dates_pkey')
    )
    # ### end Alembic commands ###
