"""empty message

Revision ID: d9e7e751f585
Revises: 9614f9a09c82
Create Date: 2022-08-09 22:48:10.090874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7e751f585'
down_revision = '9614f9a09c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_constraint('venue_name_key', 'venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venue_name_key', 'venue', ['name'])
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
