"""empty message

Revision ID: f46f6efca75f
Revises: ef55c4d0c5b9
Create Date: 2022-08-10 02:20:26.811786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46f6efca75f'
down_revision = 'ef55c4d0c5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
